/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SplitsIdRouteImport } from './routes/splits/$id'
import { Route as ExpensesIdRouteImport } from './routes/expenses/$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SplitsIdRoute = SplitsIdRouteImport.update({
  id: '/splits/$id',
  path: '/splits/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ExpensesIdRoute = ExpensesIdRouteImport.update({
  id: '/expenses/$id',
  path: '/expenses/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/expenses/$id': typeof ExpensesIdRoute
  '/splits/$id': typeof SplitsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/expenses/$id': typeof ExpensesIdRoute
  '/splits/$id': typeof SplitsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/expenses/$id': typeof ExpensesIdRoute
  '/splits/$id': typeof SplitsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/expenses/$id' | '/splits/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/expenses/$id' | '/splits/$id'
  id: '__root__' | '/' | '/expenses/$id' | '/splits/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ExpensesIdRoute: typeof ExpensesIdRoute
  SplitsIdRoute: typeof SplitsIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/splits/$id': {
      id: '/splits/$id'
      path: '/splits/$id'
      fullPath: '/splits/$id'
      preLoaderRoute: typeof SplitsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/expenses/$id': {
      id: '/expenses/$id'
      path: '/expenses/$id'
      fullPath: '/expenses/$id'
      preLoaderRoute: typeof ExpensesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ExpensesIdRoute: ExpensesIdRoute,
  SplitsIdRoute: SplitsIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
